// src/layouts/app/AppFooter.vue
﻿<script setup lang="ts">
import { VIconBtn } from 'vuetify/labs/VIconBtn';

interface Link {
    name: string;
    link: string;
    icon: string;
}

const links: Link[] = [
    {
        name: 'GitHub',
        link: 'https://github.com/NewXesTeam/new-xes-frontend',
        icon: 'mdi-github',
    },
];

const openLink = (link: string) => window.open(link, '_blank');
</script>

<template>
    <div class="flex justify-between bg-neutral-100 px-4 py-1 text-black">
        <div class="flex items-center">
            <span>Copyright by NewXesTeam 2025</span>
        </div>
        <div class="flex items-center">
            <v-icon-btn
                v-for="link of links"
                :icon="link.icon"
                :title="link.name"
                :key="link.name"
                @click="openLink(link.link)"
                v-ripple
            />
        </div>
    </div>
</template>

<style scoped></style>

// app/layout/AppFooter.tsx
﻿import * as React from 'react';
import { Button } from '@mui/material';
import { GitHub } from '@mui/icons-material';

export default function AppFooter() {
    return (
        <div className="flex justify-between bg-neutral-200 px-4 py-1 text-black">
            <div className="flex items-center">
                <span>Copyright by NewXesTeam 2025</span>
            </div>
            <div className="flex items-center">
                <Button onClick={() => window.open('https://github.com/NewXesTeam/new-xes-frontend')}>
                    <GitHub className="text-black" aria-label="GitHub" />
                </Button>
            </div>
        </div>
    );
}
