// src/layouts/app/AppLayout.vue
﻿<script setup lang="ts">
import AppNavbar from '@/layouts/app/AppNavbar.vue';
import AppFooter from '@/layouts/app/AppFooter.vue';
</script>

<template>
    <div class="flex flex-col min-h-full">
        <AppNavbar />
        <div class="mt-5 mb-5 flex-1">
            <slot />
        </div>
        <AppFooter />
    </div>
</template>

<style scoped></style>

// app/layout/AppLayout.tsx
﻿import * as React from 'react';
import AppNavbar from '@/layout/AppNavbar';
import AppFooter from '@/layout/AppFooter';

export default function AppLayout({ children }: { children: React.ReactNode }) {
    return (
        <div className="flex flex-col min-h-full">
            <AppNavbar />
            <div className="mt-5 mb-5 flex-1">{children}</div>
            <AppFooter />
        </div>
    );
}
