// src/components/work/WorkCard.vue
﻿<script setup lang="ts">
import { getWorkLink } from '@/utils/index.ts';
import type { Work } from '@/types/work.ts';
import { computed } from 'vue';
import CardActionArea from '@/components/common/CardActionArea.vue';

const { work } = defineProps<{ work: Work }>();
const thumbnail = computed(
    () => work.thumbnail || 'https://static0-test.xesimg.com/programme/assets/c16477eaab146fbc22a050e2203f91b8.png',
);
const name = computed(() => work.name.replace(/<em>|<\/em>/g, ''));

const onOpenAuthorHome = () => {
    window.open(`/space/${work.user_id}/home`, '_blank');
};
</script>

<template>
    <v-card v-tooltip:top="work.created_at">
        <CardActionArea :href="getWorkLink(work)" rel="noopener" target="_blank">
            <v-img
                class="mx-auto"
                style="width: 224px; height: 168px"
                draggable="false"
                :src="thumbnail"
                :alt="work.name"
            />

            <v-card-title v-tooltip:bottom="name">
                {{ name }}
            </v-card-title>
        </CardActionArea>

        <v-card-actions class="flex justify-between">
            <v-btn @click="onOpenAuthorHome" color="primary">
                {{ work.username }}
            </v-btn>
            <div class="flex gap-2 pr-2" style="zoom: 0.75">
                <v-badge color="info" :content="work.views" label="浏览量">
                    <v-icon icon="mdi-eye" />
                </v-badge>
                <v-badge color="primary" :content="work.likes" label="点赞数">
                    <v-icon icon="mdi-heart" />
                </v-badge>
                <v-badge color="error" :content="work.unlikes" label="点赞数">
                    <v-icon icon="mdi-thumb-down" />
                </v-badge>
                <v-badge color="success" :content="work.comments" label="评论数">
                    <v-icon icon="mdi-comment-text" />
                </v-badge>
            </div>
        </v-card-actions>
    </v-card>
</template>

<style scoped></style>

// app/components/WorkCard.tsx
import * as React from 'react';
import {
    Badge,
    Card,
    CardMedia,
    CardContent,
    CardActionArea,
    CardActions,
    Typography,
    Tooltip,
    Button,
} from '@mui/material';
import { getWorkLink } from '@/utils';
import VisibilityIcon from '@mui/icons-material/Visibility';
import FavoriteIcon from '@mui/icons-material/Favorite';
import ThumbDownIcon from '@mui/icons-material/ThumbDown';
import CommentIcon from '@mui/icons-material/Comment';
import type { Work } from '@/interfaces/work';

const WorkCard = ({ work }: { work: Work }) => {
    let link = getWorkLink(work);
    let author_url = `/space/${work.user_id}/home`;

    if (!work.name) {
        return null;
    }

    return (
        <Card>
            <Tooltip placement="top" title={work.created_at}>
                <CardActionArea onClick={() => window.open(link, '_blank')}>
                    <CardMedia
                        component="img"
                        alt={work.name.replace(/<em>|<\/em>/g, '')}
                        width={224}
                        height={168}
                        style={{ cursor: 'pointer' }}
                        src={
                            work.thumbnail ||
                            'https://static0-test.xesimg.com/programme/assets/c16477eaab146fbc22a050e2203f91b8.png'
                        }
                    />

                    <CardContent>
                        <Typography className="text-neutral-600" sx={{ fontSize: 20 }}>
                            {work.name.replace(/<em>|<\/em>/g, '')}
                        </Typography>
                    </CardContent>
                </CardActionArea>
            </Tooltip>

            <CardActions className="flex justify-between">
                <Button className="text-neutral-500" onClick={() => window.open(author_url, '_blank')}>
                    {work.username}
                </Button>

                <div className="flex gap-2" style={{ zoom: 0.75 }}>
                    <Badge badgeContent={work.views} color="info" aria-label="浏览量" showZero>
                        <VisibilityIcon />
                    </Badge>
                    <Badge badgeContent={work.likes} color="primary" aria-label="点赞数" showZero>
                        <FavoriteIcon />
                    </Badge>
                    <Badge badgeContent={work.unlikes} color="error" aria-label="点踩数" showZero>
                        <ThumbDownIcon />
                    </Badge>
                    <Badge badgeContent={work.comments} color="success" aria-label="评论数" showZero>
                        <CommentIcon />
                    </Badge>
                </div>
            </CardActions>
        </Card>
    );
};

const RemovedWorkCard = () => {
    return (
        <Card className="mb-3">
            <CardContent>
                <Typography component="div" sx={{ fontSize: 16 }}>
                    作品已被下架
                </Typography>
            </CardContent>
        </Card>
    );
};

const SmallWorkCard = ({ work }: { work: Work }) => {
    return (
        <Tooltip placement="top" title={`👀${work.views} 👍${work.likes} 👎${work.unlikes} ${work.created_at}`}>
            <Card>
                <CardActionArea onClick={() => window.open(getWorkLink(work), '_blank')}>
                    <CardMedia>
                        <img className="mx-auto" src={work.thumbnail} alt={work.name} style={{ maxHeight: 138 }} />
                    </CardMedia>
                    <CardContent>
                        <Typography sx={{ fontSize: 16 }}>{work.name}</Typography>
                    </CardContent>
                </CardActionArea>
            </Card>
        </Tooltip>
    );
};

export default WorkCard;
export { RemovedWorkCard, SmallWorkCard };
