// src/components/WorkCard.vue
﻿<script setup lang="ts">
import { getWorkLink } from '@/utils.ts';
import type { Work } from '@/types/work.js';
import { computed } from 'vue';

const { work } = defineProps<{ work: Work; }>();
const thumbnail = computed(() => (work.thumbnail || 'https://static0-test.xesimg.com/programme/assets/c16477eaab146fbc22a050e2203f91b8.png'));
const name = computed(() => work.name.replace(/<em>|<\/em>/g, ''));
</script>

<template>
    <v-card :href="getWorkLink(work)" rel="noopener" target="_blank" v-tooltip:top="work.created_at">
        <v-img class="mx-auto" style="width: 224px; height: 168px;" cover :src="thumbnail" />

        <v-card-title v-tooltip:bottom="name">
            {{ name }}
        </v-card-title>

        <v-card-actions class="flex justify-between">
            <v-btn>
                {{ work.username }}
            </v-btn>
            <div class="flex gap-2 pr-2" style="zoom: 0.75;">
                <v-badge color="info" :content="work.views" label="浏览量">
                    <v-icon icon="mdi-eye"/>
                </v-badge>
                <v-badge color="primary" :content="work.likes" label="点赞数">
                    <v-icon icon="mdi-heart"/>
                </v-badge>
                <v-badge color="error" :content="work.unlikes" label="点赞数">
                    <v-icon icon="mdi-thumb-down"/>
                </v-badge>
                <v-badge color="success" :content="work.comments" label="评论数">
                    <v-icon icon="mdi-comment-text"/>
                </v-badge>
            </div>
        </v-card-actions>
    </v-card>
</template>

<style scoped></style>

// app/components/WorkCard.tsx
import * as React from 'react';
import { Badge, Card, CardMedia, CardContent, Typography, Tooltip } from '@mui/material';
import { getWorkLink } from '@/utils';
import type { Work } from '@/interfaces/work';

const WorkCard = ({ work }: { work: Work }) => {
    let link = getWorkLink(work);
    let author_url = `/space/${work.user_id}/home`;

    if (!work.name) {
        return null;
    }

    return (
        <Tooltip placement="top" title={work.created_at}>
            <Card className="mb-3 position-relative">
                <CardMedia
                    component="img"
                    alt={work.name.replace(/<em>|<\/em>/g, '')}
                    width={224}
                    height={168}
                    src={
                        work.thumbnail ||
                        'https://static0-test.xesimg.com/programme/assets/c16477eaab146fbc22a050e2203f91b8.png'
                    }
                />

                <CardContent>
                    <Tooltip placement="top" title={work.name.replace(/<em>|<\/em>/g, '')}>
                        <Typography
                            sx={{
                                overflow: 'hidden',
                                textOverflow: 'ellipsis',
                                whiteSpace: 'nowrap',
                                color: 'blue',
                                fontSize: '16px',
                            }}
                            gutterBottom
                            variant="h5"
                            component="div"
                        >
                            <a href={link} className="text-decoration-none stretched-link" target="_blank">
                                {work.name.replace(/<em>|<\/em>/g, '')}
                            </a>
                        </Typography>
                    </Tooltip>

                    <div className="d-flex justify-content-between align-items-center">
                        <a href={author_url} target="_blank" style={{ zIndex: 2 }}>
                            <span style={{ fontSize: '14px' }}>{work.username}</span>
                        </a>
                        <div style={{ display: 'flex', gap: '10px' }}>
                            <Badge badgeContent={work.views} color="info" aria-label="浏览量" showZero>
                                👀
                            </Badge>
                            <Badge badgeContent={work.likes} color="primary" aria-label="点赞数" showZero>
                                👍
                            </Badge>
                            <br />
                            <Badge badgeContent={work.unlikes} color="error" aria-label="点踩数" showZero>
                                👎
                            </Badge>
                            <Badge badgeContent={work.comments} color="success" aria-label="评论数" showZero>
                                💬
                            </Badge>
                        </div>
                    </div>
                </CardContent>
            </Card>
        </Tooltip>
    );
};

const RemovedWorkCard = () => {
    return (
        <Card className="mb-3">
            <CardContent>
                <Typography variant="h5" component="div">
                    作品已被下架
                </Typography>
            </CardContent>
        </Card>
    );
};

const SmallWorkCard = ({ work }: { work: Work }) => {
    return (
        <Tooltip
            placement="top"
            title={`
            👀${work.views} 👍${work.likes} 👎${work.unlikes}
            ${work.created_at}
        `}
        >
            <Tooltip placement="bottom" title={work.name}>
                <Card>
                    <Typography
                        sx={{
                            overflow: 'hidden',
                            textOverflow: 'ellipsis',
                            whiteSpace: 'nowrap',
                            color: 'blue',
                            fontSize: '16px',
                            maxWidth: '100px',
                        }}
                        gutterBottom
                        variant="h5"
                        component="div"
                    >
                        <a href={getWorkLink(work)} className="stretched-link">
                            {work.name}
                        </a>
                    </Typography>
                    <CardContent className="py-0">
                        <img src={work.thumbnail} height={138} className="m-auto" alt={work.name} />
                    </CardContent>
                </Card>
            </Tooltip>
        </Tooltip>
    );
};

export default WorkCard;
export { RemovedWorkCard, SmallWorkCard };
