// src/components/work/WorkList.vue
﻿<script setup lang="ts">
import type { Work } from '@/types/work.ts';
import WorkCard from '@/components/work/WorkCard.vue';
import RemovedWorkCard from '@/components/work/RemovedWorkCard.vue';
import { v4 as uuid } from 'uuid';
import { useAttrs } from 'vue';

interface Props {
    enableRemoved?: boolean;
    className?: string;
    works: Work[];
    WorkCardInterface?: typeof WorkCard;
}

const attrs = useAttrs();

const {
    enableRemoved = false,
    className = 'm-4 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-2',
    works,
    WorkCardInterface = WorkCard,
} = defineProps<Props>();
</script>

<template>
    <div :class="className">
        <!-- 先尝试 id，不存在可能是作品被下架了尝试 topic_id，还不存在就 tmd 是学某思搞的 null 作品 -->
        <component
            v-for="work of works"
            :key="work?.id || work?.topic_id || uuid()"
            :is="enableRemoved ? WorkCardInterface : work && !work.removed ? WorkCardInterface : RemovedWorkCard"
            :work="work"
            v-bind="attrs"
        />
    </div>
</template>

<style scoped></style>

// app/components/WorkList.tsx
import * as React from 'react';
import type { Work } from '@/interfaces/work';
import { Grid } from '@mui/material';
import WorkCard from './WorkCard';
import { RemovedWorkCard } from './WorkCard';

const WorkList = ({
    works,
    className = '',
    enableRemoved = true,
    WorkCardInterface = WorkCard,
}: {
    works: Work[];
    className?: string;
    enableRemoved?: boolean;
    WorkCardInterface?: ({ work }: { work: Work }) => React.JSX.Element | null;
}) => {
    const cards = works.map((work: Work) => {
        if (work === null) {
            return null;
        } else if (work.removed && enableRemoved) {
            return (
                <Grid key={work.topic_id} size={{ xs: 6, sm: 4, md: 3, lg: 2.4, xl: 2.4 }}>
                    <RemovedWorkCard />
                </Grid>
            );
        } else {
            return (
                <Grid key={work.topic_id} size={{ xs: 6, sm: 4, md: 3, lg: 2.4, xl: 2.4 }}>
                    <WorkCardInterface work={work} />
                </Grid>
            );
        }
    });

    return (
        <Grid container spacing={2} className={className}>
            {cards}
        </Grid>
    );
};

export default WorkList;
