// src/userInfo.tsx
import * as React from 'react';
import { createRoot } from 'react-dom/client';
import { UserInfo } from '@/interfaces/user';
import { SpaceProfile } from '@/interfaces/space';
import { checkLoggedIn } from '@/utils';
import { Table, Container } from 'react-bootstrap';
import NavbarComponent from '@/components/Navbar';
import '@/styles/common.scss';

const UserInfoPage = () => {
    if (!checkLoggedIn()) {
        location.href = '/login.html';
        return null;
    }

    const [info, setInfo] = React.useState<React.JSX.Element | string>('Loading...');

    React.useEffect(() => {
        let ignore = false;

        const func = async () => {
            const infoResponse = await fetch('/api/user/info');
            const infoResponseData: UserInfo = await infoResponse.json();
            const spaceProfileResponse = await fetch(`/api/space/profile?user_id=${infoResponseData.data.user_id}`);
            const spaceProfileData: SpaceProfile = await spaceProfileResponse.json();

            const sexId = infoResponseData.data.sex;
            const sexName: string = ['男', '女', '未知'][Number(sexId) - 1];

            setInfo(
                <>
                    <div>
                        <img src={infoResponseData.data.avatar_path} alt="头像" />
                        <h2>{infoResponseData.data.realname}</h2>
                        <h3 color="red">
                            Dangerous: 消息中心的“点赞与收藏”部分的api有问题，会返回包括但不限于下面他人不可见的内容。
                        </h3>
                    </div>
                    <Table>
                        <thead>
                            <tr>
                                <th>属性</th>
                                <th>值</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th>用户 ID</th>
                                <td>{infoResponseData.data.user_id}</td>
                            </tr>
                            <tr>
                                <th>用户名（他人不可见）</th>
                                <td>{infoResponseData.data.name}</td>
                            </tr>
                            <tr>
                                <th>真名</th>
                                <td>{infoResponseData.data.realname}</td>
                            </tr>
                            <tr>
                                <th>昵称（他人不可见）</th>
                                <td>{infoResponseData.data.nickname}</td>
                            </tr>
                            <tr>
                                <th>英文名（他人不可见）</th>
                                <td>{infoResponseData.data.en_name}</td>
                            </tr>
                            <tr>
                                <th>性别（他人不可见）</th>
                                <td>{sexName}</td>
                            </tr>
                            <tr>
                                <th>头像 URL</th>
                                <td>{infoResponseData.data.avatar_path}</td>
                            </tr>
                            <tr>
                                <th>创建时间（他人不可见）</th>
                                <td>{infoResponseData.data.create_time}</td>
                            </tr>
                            <tr>
                                <th>年级名称（他人不可见）</th>
                                <td>{infoResponseData.data.grade_name}</td>
                            </tr>
                            <tr>
                                <th>个人签名</th>
                                <td>{spaceProfileData.data.signature}</td>
                            </tr>
                            <tr>
                                <th>关注数量</th>
                                <td>{spaceProfileData.data.follows}</td>
                            </tr>
                            <tr>
                                <th>粉丝数量</th>
                                <td>{spaceProfileData.data.fans}</td>
                            </tr>
                        </tbody>
                    </Table>
                </>,
            );
        };

        if (!ignore) func();
        return () => {
            ignore = true;
        };
    }, []);

    return (
        <>
            <NavbarComponent />
            <Container className="mt-5">
                <h1>个人信息展示页面</h1>
                <hr />
                {info}
                <span className="d-block text-center width-100">「国之殇，未敢忘。——尸体的神韵」</span>
            </Container>
        </>
    );
};

const dom: HTMLElement | null = document.getElementById('app');
if (dom) {
    const root = createRoot(dom);
    root.render(
        <React.StrictMode>
            <UserInfoPage />
        </React.StrictMode>,
    );
} else {
    throw new Error('Cannot find dom element #app');
}

// src/pages/code.xueersi.com/userInfo.vue
<script setup lang="ts">
import { computed, onMounted, watch } from 'vue';
import { useAppStore } from '@/stores/app.ts';
import Loading from '@/components/common/Loading.vue';
import { useFetchData } from '@/utils/index.ts';
import type { SpaceProfile } from '@/types/space.ts';

const store = useAppStore();

const [spaceData, loadSpaceData] = useFetchData<SpaceProfile>(
    () => `/api/space/profile?user_id=${store.userInfo?.user_id}`,
);
const sexName = computed(() => ['男', '女', '未知'][Math.max(Number(store.userInfo?.sex) - 1, 0)]);

watch(
    () => store.loaded,
    loaded => {
        if (!loaded) return;
        if (!store.isLoggedIn) {
            location.href = 'https://login.xueersi.com/';
            return;
        }

        loadSpaceData();
    },
);

onMounted(() => {
    if (!store.isLoggedIn) return;
    loadSpaceData();
});
</script>

<template>
    <h1 style="font-size: 36px">个人信息展示页面</h1>
    <v-divider />
    <Loading v-if="!spaceData.success" :error="spaceData.error" />
    <div v-else class="flex flex-col gap-2">
        <div class="flex items-center gap-2">
            <v-avatar :size="128" :image="store.userInfo?.avatar_path" />
            <div class="flex flex-col h-fit">
                <h2 style="font-size: 24px">{{ store.userInfo?.realname }}</h2>
                <h3 class="text-rose-600 dark:text-rose-400">
                    Dangerous: 消息中心的“点赞与收藏”部分的api有问题，会返回包括但不限于下面他人不可见的内容。
                </h3>
            </div>
        </div>
        <v-table>
            <thead>
                <tr>
                    <th>属性</th>
                    <th>值</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th>用户 ID</th>
                    <th>{{ store.userInfo?.user_id }}</th>
                </tr>
                <tr>
                    <th>用户名（他人不可见）</th>
                    <th>{{ store.userInfo?.name }}</th>
                </tr>
                <tr>
                    <th>真名</th>
                    <th>{{ store.userInfo?.realname }}</th>
                </tr>
                <tr>
                    <th>昵称（他人不可见）</th>
                    <th>{{ store.userInfo?.nickname }}</th>
                </tr>
                <tr>
                    <th>英文名（他人不可见）</th>
                    <th>{{ store.userInfo?.en_name }}</th>
                </tr>
                <tr>
                    <th>性别</th>
                    <th>{{ sexName }}</th>
                </tr>
                <tr>
                    <th>头像 URL</th>
                    <th>{{ store.userInfo?.avatar_path }}</th>
                </tr>
                <tr>
                    <th>创建时间（他人不可见）</th>
                    <th>{{ store.userInfo?.create_time }}</th>
                </tr>
                <tr>
                    <th>年级名称（他人不可见）</th>
                    <th>{{ store.userInfo?.grade_name }}</th>
                </tr>
                <tr>
                    <th>个人签名</th>
                    <th>{{ spaceData.data?.signature }}</th>
                </tr>
                <tr>
                    <th>关注数量</th>
                    <th>{{ spaceData.data?.follows }}</th>
                </tr>
                <tr>
                    <th>粉丝数量</th>
                    <th>{{ spaceData.data?.fans }}</th>
                </tr>
            </tbody>
        </v-table>
    </div>
    <span class="block text-center w-full">「国之殇，未敢忘。——尸体的神韵」</span>
</template>

<style scoped></style>
