// src/components/ProjectPublishModal.vue
<script setup lang="ts">
import { PublishWorkInfo } from '@/types/work';
import { ref } from 'vue';
import Tagify from './Tagify.vue';
import { useAlertsStore } from '@/stores/alerts';

const { work } = defineProps<{ work: PublishWorkInfo }>();
const thumnailImage = ref(
    work.thumbnail || 'https://static0.xesimg.com/talcode/assets/py/default-python-thumbnail.png',
);
const workName = ref(work.name);
const description = ref('');
const origin = ref(work.created_source || 'original');
const tagText = ref();

const alertsStore = useAlertsStore();
const isActive = ref(false);

const handleTagsChange = (event: CustomEvent) => {
    console.log(event);
    const tags: { value: string }[] = event.detail.tagify.getCleanValue();
    let tag_str = '';
    tags.forEach(tag => {
        tag_str += tag.value.replaceAll(' ', '&nbsp;') + ' ';
    });
    tagText.value = tag_str;
};

let lang = work.lang;
if (lang === 'webpy' || lang === 'python') {
    lang = 'python';
} else if (lang === 'cpp') {
    lang = 'compilers';
} else {
    lang = 'projects';
}

const onClickPublish = async () => {
    if (workName.value.length === 0 || tagText.value.length === 0) {
        alertsStore.addAlert({
            type: 'warning',
            text: '有选项未填写！',
        });
        return;
    }

    try {
        await fetch(`/api/${lang}/${work.id}/publish`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                projectId: work.id,
                name: workName.value,
                tags: tagText.value.trimEnd(),
                created_source: origin.value,
                thumbnail: thumnailImage.value,
                hidden_code: 2,
                description: description.value,
            }),
        });
        isActive.value = false;
        alertsStore.addAlert({
            type: 'success',
            text: '已发布',
        });
        location.reload();
    } catch (error) {
        alertsStore.addAlert({
            type: 'error',
            text: '发布失败，请重试',
        });
    }
};
</script>

<template>
    <v-dialog max-width="800" v-model="isActive">
        <template v-slot:activator="{ props: activatorProps }">
            <v-btn
                xSmall
                color="green"
                v-if="work.published === 0 && !work.removed"
                class="px-1 mr-1"
                v-bind="activatorProps"
            >
                <v-icon icon="mdi-publish"></v-icon>
                发布
            </v-btn>
        </template>

        <template v-slot:default="{ isActive }">
            <v-card>
                <v-card-text class="flex gap-4 flex-wrap">
                    <div class="flex-1">
                        <h4 class="font-weight-bold">作品封面</h4>

                        <div class="overflow-hidden rounded">
                            <v-img :src="thumnailImage" alt="作品封面" />
                        </div>
                    </div>
                    <div class="flex-1">
                        <v-form>
                            <v-text-field label="作品名称" v-model="workName"></v-text-field>

                            <v-radio-group label="作品来源" inline v-model="origin">
                                <v-radio label="原创" value="original"></v-radio>
                                <v-radio label="改编" value="adapt"></v-radio>
                                <v-radio label="转载" value="reprint"></v-radio>
                            </v-radio-group>

                            <Tagify
                                :settings="{
                                    whitelist: ['游戏', '动画', '故事', '模拟', '艺术', '教程', '其他'],
                                    placeholder: '添加标签',
                                    dropdown: { enabled: 0 },
                                }"
                                @change="handleTagsChange"
                            />

                            <v-textarea class="mt-4" label="作品描述" v-model="description"></v-textarea>
                        </v-form>
                    </div>
                </v-card-text>

                <v-card-actions>
                    <v-spacer></v-spacer>

                    <v-btn text="取消" @click="isActive.value = false"></v-btn>

                    <v-btn @click="onClickPublish"> 发布 </v-btn>
                </v-card-actions>
            </v-card>
        </template>
    </v-dialog>
</template>

<style scoped></style>

// src/components/ProjectPublishModal.tsx
import * as React from 'react';
import { Modal, Button, Form, Row, Col } from 'react-bootstrap';
import AutoCloseAlert from '@/components/AutoCloseAlert';
import { PublishWorkInfo } from '@/interfaces/work';
import '@/styles/common.scss';

const ProjectPublishModal = ({
    workInfo,
    isShow,
    setIsShow,
}: {
    workInfo: PublishWorkInfo;
    isShow: boolean;
    setIsShow: (show: boolean) => void;
}) => {
    const [alerts, setAlerts] = React.useState<React.JSX.Element[]>([]);
    const [work, setWork] = React.useState<PublishWorkInfo>(workInfo);

    let lang = workInfo.lang;
    if (lang === 'webpy' || lang === 'python') {
        lang = 'python';
    } else if (lang === 'cpp') {
        lang = 'compilers';
    } else {
        lang = 'projects';
    }

    const onClickPublish = async () => {
        if (workNameRef.current.value === '' || workTagsRef.current === '') {
            setAlerts([<AutoCloseAlert variant="warning">有选项未填写！</AutoCloseAlert>, ...alerts]);
            return;
        }
        await fetch(`/api/${lang}/${work.id}/publish`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                projectId: work.id,
                name: workNameRef.current.value,
                tags: workTagsRef.current.trimEnd(),
                created_source: origin,
                thumbnail: thumbnailImage,
                hidden_code: 2,
                description: descriptionTextRef.current.value,
            }),
        });
        setIsShow(false);
        setAlerts([<AutoCloseAlert variant="suceess">已发布</AutoCloseAlert>, ...alerts]);
    };

    // 提交内容
    const workNameRef = React.useRef<HTMLInputElement>(null);
    const workTagsRef = React.useRef<string>(null);
    // const thumbnailImageRef = React.useRef<HTMLImageElement>(null);
    const [thumbnailImage, setThumbnailImage] = React.useState<string>(
        work.thumbnail || 'https://static0.xesimg.com/talcode/assets/py/default-python-thumbnail.png',
    );
    const descriptionTextRef = React.useRef<HTMLTextAreaElement>(null);
    const [origin, setOrigin] = React.useState<string>(work.created_source || 'original');

    const handleChangeOrigin = (e: React.ChangeEvent<HTMLInputElement>) => {
        setOrigin(e.target.value);
    };
    const handleChangeTags = (e: React.ChangeEvent<HTMLInputElement>) => {
        // workTagsRef.current = e.target.value;
        // console.log(e.target.value);
        if (workTagsRef.current === null) workTagsRef.current = '';
        if (e.target.checked) {
            workTagsRef.current += e.target.value + ' ';
        } else {
            workTagsRef.current = workTagsRef.current.replace(e.target.value + ' ', '');
        }
        // console.log(workTagsRef.current);
    };

    React.useEffect(() => {
        let ignore = false;
        const func = async () => {
            let now_lang = lang;
            if (lang === 'python') now_lang = 'compilers';
            const response = await fetch(`/api/${now_lang}/${work.id}?id=${work.id}`);
            const responseData = await response.json();
            setWork(responseData.data);
        };

        if (!ignore) func();
        return () => {
            ignore = true;
        };
    }, []);

    return (
        <Modal show={isShow} centered={true}>
            <Modal.Header>
                <Modal.Title>发布作品</Modal.Title>
            </Modal.Header>
            <Modal.Body>
                <div className="alert-list">{alerts}</div>
                <Row>
                    <Col sm={6}>
                        <p>作品封面</p>
                        <img src={thumbnailImage} alt="作品封面" style={{ width: '100%' }} />
                    </Col>
                    <Col sm={6}>
                        <Form.Label>* 作品名称</Form.Label>
                        <Form.Control
                            ref={workNameRef}
                            type="text"
                            placeholder="请输入作品名称"
                            defaultValue={work.name}
                        />

                        <Form.Label>* 作品来源</Form.Label>
                        <Form.Group>
                            <Form.Check
                                checked={origin === 'original'}
                                inline
                                onChange={handleChangeOrigin}
                                type="radio"
                                label="原创"
                                name="origin"
                                value="original"
                                disabled={work.created_source === 'adapt'}
                            />
                            <Form.Check
                                checked={origin === 'adapt'}
                                inline
                                onChange={handleChangeOrigin}
                                type="radio"
                                label="改编"
                                name="origin"
                                value="adapt"
                                disabled={work.created_source !== 'adapt'}
                            />
                            <Form.Check
                                checked={origin === 'reprint'}
                                inline
                                onChange={handleChangeOrigin}
                                type="radio"
                                label="转载"
                                name="origin"
                                value="reprint"
                                disabled={work.created_source === 'adapt'}
                            />
                        </Form.Group>

                        <Form.Label>*作品标签（空格分开两个标签）</Form.Label>
                        {/* <Form.Control
                            ref={workTagsRef}
                            type="text"
                            placeholder="请输入作品标签"
                            defaultValue={work.tags}
                        /> */}
                        <Form.Group>
                            <Form.Check
                                inline
                                type="checkbox"
                                label="游戏"
                                value="游戏"
                                id="游戏"
                                defaultChecked={work.tags && work.tags.includes('游戏')}
                                onChange={handleChangeTags}
                            />
                            <Form.Check
                                inline
                                type="checkbox"
                                label="动画"
                                value="动画"
                                id="动画"
                                defaultChecked={work.tags && work.tags.includes('动画')}
                                onChange={handleChangeTags}
                            />
                            <Form.Check
                                inline
                                type="checkbox"
                                label="故事"
                                value="故事"
                                id="故事"
                                defaultChecked={work.tags && work.tags.includes('故事')}
                                onChange={handleChangeTags}
                            />
                            <Form.Check
                                inline
                                type="checkbox"
                                label="模拟"
                                value="模拟"
                                id="模拟"
                                defaultChecked={work.tags && work.tags.includes('模拟')}
                                onChange={handleChangeTags}
                            />
                        </Form.Group>
                        <Form.Group>
                            <Form.Check
                                inline
                                type="checkbox"
                                label="艺术"
                                value="艺术"
                                id="艺术"
                                defaultChecked={work.tags && work.tags.includes('艺术')}
                                onChange={handleChangeTags}
                            />
                            <Form.Check
                                inline
                                type="checkbox"
                                label="教程"
                                value="教程"
                                id="教程"
                                defaultChecked={work.tags && work.tags.includes('教程')}
                                onChange={handleChangeTags}
                            />
                            <Form.Check
                                inline
                                type="checkbox"
                                label="其他"
                                value="其他"
                                id="其他"
                                defaultChecked={work.tags && work.tags.includes('其他')}
                                onChange={handleChangeTags}
                            />
                        </Form.Group>

                        <Form.Label>作品介绍</Form.Label>
                        <Form.Control
                            ref={descriptionTextRef}
                            as="textarea"
                            cols={5}
                            rows={3}
                            placeholder="请输入作品介绍"
                        />
                    </Col>
                </Row>
            </Modal.Body>
            <Modal.Footer>
                <Button variant="primary" onClick={() => setIsShow(false)}>
                    返回
                </Button>
                <Button variant="primary" onClick={() => onClickPublish()}>
                    确定发布
                </Button>
            </Modal.Footer>
        </Modal>
    );
};

export default ProjectPublishModal;
