// app/components/ProjectPublishModal.tsx
import * as React from 'react';
import {
    Dialog,
    DialogTitle,
    DialogContent,
    DialogContentText,
    DialogActions,
    Button,
    Grid,
    TextField,
    FormLabel,
    RadioGroup,
    FormControlLabel,
    Radio,
    FormControl,
} from '@mui/material';
import UploadIcon from '@mui/icons-material/UploadFile';
// @ts-ignore  // 这个不怨我
import Tags from '@yaireo/tagify/react';
import AutoCloseAlert from '@/components/AutoCloseAlert';
import CryptoJS from 'crypto-js';

import type { PublishWorkInfo } from '@/interfaces/work';
import '@yaireo/tagify/dist/tagify.css';

const ProjectPublishModal = ({
    workInfo,
    isShow,
    setIsShow,
}: {
    workInfo: PublishWorkInfo;
    isShow: boolean;
    setIsShow: (show: boolean) => void;
}) => {
    const [alerts, setAlerts] = React.useState<React.JSX.Element[]>([]);
    const [work, setWork] = React.useState<PublishWorkInfo>(workInfo);
    const [thumbnailImage, setThumbnailImage] = React.useState<string>(
        work.thumbnail || 'https://static0.xesimg.com/talcode/assets/py/default-python-thumbnail.png',
    );
    const [origin, setOrigin] = React.useState<string>(work.created_source || 'original');

    const workNameRef = React.useRef<HTMLInputElement>(null);
    const workTagsRef = React.useRef<string>('');
    const thumbnailUploadRef = React.useRef<HTMLInputElement>(null);
    const descriptionTextRef = React.useRef<HTMLTextAreaElement>(null);

    let lang = workInfo.lang;
    if (lang === 'webpy' || lang === 'python') {
        lang = 'python';
    } else if (lang === 'cpp') {
        lang = 'compilers';
    } else {
        lang = 'projects';
    }

    const onClickPublish = async () => {
        if (!workNameRef.current?.value || !workTagsRef.current) {
            setAlerts([
                <AutoCloseAlert key="warning" severity="warning">
                    有选项未填写！
                </AutoCloseAlert>,
                ...alerts,
            ]);
            return;
        }

        try {
            await fetch(`/api/${lang}/${work.id}/publish`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    projectId: work.id,
                    name: workNameRef.current.value,
                    tags: workTagsRef.current.trimEnd(),
                    created_source: origin,
                    thumbnail: thumbnailImage,
                    hidden_code: 2,
                    description: descriptionTextRef.current?.value,
                }),
            });
            setIsShow(false);
            setAlerts([
                <AutoCloseAlert key="success" severity="success">
                    已发布
                </AutoCloseAlert>,
                ...alerts,
            ]);
        } catch (error) {
            setAlerts([
                <AutoCloseAlert key="error" severity="error">
                    发布失败，请重试
                </AutoCloseAlert>,
                ...alerts,
            ]);
        }
    };

    const handleChangeOrigin = (e: React.ChangeEvent<HTMLInputElement>) => {
        setOrigin(e.target.value);
    };

    React.useEffect(() => {
        let ignore = false;
        const func = async () => {
            let now_lang = lang;
            if (lang === 'python') now_lang = 'compilers';
            const response = await fetch(`/api/${now_lang}/${work.id}?id=${work.id}`);
            const responseData = await response.json();
            setWork(responseData.data);
            setOrigin(responseData.data.created_source || 'original');
        };

        if (!ignore) func();
        return () => {
            ignore = true;
        };
    }, []);

    const handleTagsChange = (event: any) => {
        const tags: { value: string }[] = event.detail.tagify.getCleanValue();
        let tag_str = '';
        tags.forEach(tag => {
            tag_str += tag.value.replaceAll(' ', '&nbsp;') + ' ';
        });
        workTagsRef.current = tag_str;
    };

    return (
        <Dialog open={isShow} onClose={() => setIsShow(false)} maxWidth="md" fullWidth>
            <DialogTitle>发布作品</DialogTitle>

            <DialogContent>
                <div className="alert-list">{alerts}</div>

                <Grid container sx={{ display: 'flex', gap: 2, flexWrap: 'wrap' }}>
                    <div style={{ flex: 1 }}>
                        <DialogContentText sx={{ mb: 2 }}>作品封面</DialogContentText>
                        <div className="overflow-hidden rounded">
                            <img
                                src={thumbnailImage}
                                alt="作品封面"
                                style={{ width: '100%', height: '100%', display: 'block' }}
                            />
                        </div>
                        <input
                            type="file"
                            accept="image/*"
                            ref={thumbnailUploadRef}
                            style={{ display: 'none' }}
                            onChange={e => {
                                if (e.target.files && e.target.files[0]) {
                                    const reader = new FileReader();
                                    const file = e.target.files[0];
                                    // @ts-ignore
                                    const FileExtension = file.name.split('.').pop().toLowerCase();
                                    reader.readAsArrayBuffer(file);
                                    reader.onload = async e => {
                                        if (e.target && e.target.result) {
                                            const ThumbnailImageArrayBuffer = e.target.result as ArrayBuffer;
                                            const wordArray = CryptoJS.lib.WordArray.create(ThumbnailImageArrayBuffer);
                                            const md5 = CryptoJS.MD5(wordArray).toString();

                                            const reader2 = new FileReader();
                                            reader2.readAsText(file);
                                            reader2.onload = async e => {
                                                if (md5 && e.target && e.target.result) {
                                                    const response = await fetch(
                                                        `/api/assets/get_tss_upload_params?filename=${md5}.${FileExtension}&md5=${md5}&scene=thumbnail`,
                                                    );
                                                    const responseData = await response.json();
                                                    await fetch(responseData.data.host, {
                                                        method: 'PUT',
                                                        headers: responseData.data.headers,
                                                        body: e.target.result,
                                                    });
                                                    setThumbnailImage(responseData.data.url);
                                                }
                                            };
                                        }
                                    };
                                }
                            }}
                        />
                        <Button
                            variant="contained"
                            startIcon={<UploadIcon />}
                            onClick={() => {
                                if (thumbnailUploadRef.current) {
                                    thumbnailUploadRef.current.click();
                                }
                            }}
                        >
                            上传封面
                        </Button>
                    </div>

                    <div style={{ flex: 1 }}>
                        <FormControl fullWidth required margin="normal">
                            <FormLabel>作品名称</FormLabel>
                            <TextField
                                inputRef={workNameRef}
                                placeholder="请输入作品名称"
                                defaultValue={work.name}
                                variant="outlined"
                            />
                        </FormControl>

                        <FormControl component="fieldset" fullWidth required margin="normal">
                            <FormLabel>作品来源</FormLabel>
                            <RadioGroup row value={origin} onChange={handleChangeOrigin} name="origin">
                                <FormControlLabel
                                    value="original"
                                    label="原创"
                                    control={<Radio />}
                                    disabled={work.created_source === 'adapt'}
                                />
                                <FormControlLabel
                                    value="adapt"
                                    label="改编"
                                    control={<Radio />}
                                    disabled={work.created_source !== 'adapt'}
                                />
                                <FormControlLabel
                                    value="reprint"
                                    label="转载"
                                    control={<Radio />}
                                    disabled={work.created_source === 'adapt'}
                                />
                            </RadioGroup>
                        </FormControl>

                        <FormControl fullWidth required margin="normal">
                            <FormLabel>作品标签</FormLabel>
                            <Tags
                                whitelist={['游戏', '动画', '故事', '模拟', '艺术', '教程', '其他']}
                                placeholder="添加标签"
                                settings={{ dropdown: { enabled: 0 } }}
                                onChange={handleTagsChange}
                            />
                        </FormControl>

                        <FormControl fullWidth margin="normal">
                            <FormLabel>作品介绍</FormLabel>
                            <TextField
                                inputRef={descriptionTextRef}
                                placeholder="请输入作品介绍"
                                multiline
                                rows={3}
                                variant="outlined"
                            />
                        </FormControl>
                    </div>
                </Grid>
            </DialogContent>

            <DialogActions>
                <Button onClick={() => setIsShow(false)}>返回</Button>
                <Button onClick={onClickPublish} color="primary">
                    确定发布
                </Button>
            </DialogActions>
        </Dialog>
    );
};

export default ProjectPublishModal;

// src/components/ProjectPublishModal.vue
<script setup lang="ts">
import { PublishWorkInfo } from '@/types/work';
import { ref } from 'vue';
import Tagify from './Tagify.vue';
import { useAlertsStore } from '@/stores/alerts';
import CryptoJS from 'crypto-js';

const { work } = defineProps<{ work: PublishWorkInfo }>();
const thumnailImage = ref(
    work.thumbnail || 'https://static0.xesimg.com/talcode/assets/py/default-python-thumbnail.png',
);
const thumbnailUploadRef = ref<HTMLInputElement | null>(null);

const workName = ref(work.name);
const description = ref('');
const origin = ref(work.created_source || 'original');
const tagText = ref();

const alertsStore = useAlertsStore();
const isActive = ref(false);

const handleTagsChange = (event: CustomEvent) => {
    console.log(event);
    const tags: { value: string }[] = event.detail.tagify.getCleanValue();
    let tag_str = '';
    tags.forEach(tag => {
        tag_str += tag.value.replaceAll(' ', '&nbsp;') + ' ';
    });
    tagText.value = tag_str;
};

let lang = work.lang;
if (lang === 'webpy' || lang === 'python') {
    lang = 'python';
} else if (lang === 'cpp') {
    lang = 'compilers';
} else {
    lang = 'projects';
}

const handleThumbnailUpload = (event: Event) => {
    const target = event.target as HTMLInputElement;
    if (target.files && target.files[0]) {
        const reader = new FileReader();
        const file = target.files[0];
        const fileExtension = file.name.split('.').pop()?.toLowerCase() || 'png';

        reader.readAsArrayBuffer(file);
        reader.onload = async e => {
            if (e.target?.result) {
                const arrayBuffer = e.target.result as ArrayBuffer;
                const wordArray = CryptoJS.lib.WordArray.create(arrayBuffer);
                const md5 = CryptoJS.MD5(wordArray).toString();

                const reader2 = new FileReader();
                reader2.readAsArrayBuffer(file);
                reader2.onload = async e2 => {
                    if (md5 && e2.target?.result) {
                        try {
                            const res = await fetch(
                                `/api/assets/get_tss_upload_params?filename=${md5}.${fileExtension}&md5=${md5}&scene=thumbnail`,
                            );
                            const data = await res.json();

                            await fetch(data.data.host, {
                                method: 'PUT',
                                headers: data.data.headers,
                                body: e2.target.result,
                            });

                            thumnailImage.value = data.data.url;
                            alertsStore.addAlert({
                                type: 'success',
                                text: '封面上传成功',
                            });
                        } catch (err) {
                            alertsStore.addAlert({
                                type: 'error',
                                text: '封面上传失败，请重试',
                            });
                        }
                    }
                };
            }
        };
    }
};

const triggerUpload = () => {
    thumbnailUploadRef.value?.click();
};

const onClickPublish = async () => {
    if (workName.value.length === 0 || tagText.value.length === 0) {
        alertsStore.addAlert({
            type: 'warning',
            text: '有选项未填写！',
        });
        return;
    }

    try {
        await fetch(`/api/${lang}/${work.id}/publish`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                projectId: work.id,
                name: workName.value,
                tags: tagText.value.trimEnd(),
                created_source: origin.value,
                thumbnail: thumnailImage.value,
                hidden_code: 2,
                description: description.value,
            }),
        });
        isActive.value = false;
        alertsStore.addAlert({
            type: 'success',
            text: '已发布',
        });
        location.reload();
    } catch (error) {
        alertsStore.addAlert({
            type: 'error',
            text: '发布失败，请重试',
        });
    }
};
</script>

<template>
    <v-dialog max-width="800" v-model="isActive">
        <template v-slot:activator="{ props: activatorProps }">
            <v-btn
                xSmall
                color="green"
                v-if="work.published === 0 && !work.removed"
                class="px-1 mr-1"
                v-bind="activatorProps"
            >
                <v-icon icon="mdi-publish"></v-icon>
                发布
            </v-btn>
        </template>

        <template v-slot:default="{ isActive }">
            <v-card>
                <v-card-text class="flex gap-4 flex-wrap">
                    <div class="flex-1">
                        <h4 class="font-weight-bold">作品封面</h4>

                        <div class="overflow-hidden rounded mb-3">
                            <v-img :src="thumnailImage" alt="作品封面" height="200" cover />
                        </div>

                        <input
                            ref="thumbnailUploadRef"
                            type="file"
                            accept="image/*"
                            style="display: none"
                            @change="handleThumbnailUpload"
                        />

                        <v-btn color="primary" block @click="triggerUpload">
                            <v-icon icon="mdi-upload"></v-icon>
                            上传封面
                        </v-btn>
                    </div>

                    <div class="flex-1">
                        <v-form>
                            <v-text-field label="作品名称" v-model="workName"></v-text-field>

                            <v-radio-group label="作品来源" inline v-model="origin">
                                <v-radio label="原创" value="original" :disabled="work.created_source === 'adapt'"></v-radio>
                                <v-radio label="改编" value="adapt" :disabled="work.created_source !== 'adapt'"></v-radio>
                                <v-radio label="转载" value="reprint" :disabled="work.created_source === 'adapt'"></v-radio>
                            </v-radio-group>

                            <Tagify
                                :settings="{
                                    whitelist: ['游戏', '动画', '故事', '模拟', '艺术', '教程', '其他'],
                                    placeholder: '添加标签',
                                    dropdown: { enabled: 0 },
                                }"
                                @change="handleTagsChange"
                            />

                            <v-textarea class="mt-4" label="作品描述" v-model="description"></v-textarea>
                        </v-form>
                    </div>
                </v-card-text>

                <v-card-actions>
                    <v-spacer></v-spacer>
                    <v-btn text @click="isActive.value = false">取消</v-btn>
                    <v-btn color="success" @click="onClickPublish">发布</v-btn>
                </v-card-actions>
            </v-card>
        </template>
    </v-dialog>
</template>

<style scoped></style>
