// src/components/WorkCard.vue
﻿<script setup lang="ts">
import { getWorkLink } from '@/utils.ts';
import type { Work } from '@/types/work.js';
import { computed } from 'vue';

const { work } = defineProps<{ work: Work; }>();
const thumbnail = computed(() => (work.thumbnail || 'https://static0-test.xesimg.com/programme/assets/c16477eaab146fbc22a050e2203f91b8.png'));
const name = computed(() => work.name.replace(/<em>|<\/em>/g, ''));
</script>

<template>
    <v-card :href="getWorkLink(work)" rel="noopener" target="_blank" v-tooltip:top="work.created_at">
        <v-img class="mx-auto" style="width: 224px; height: 168px;" cover :src="thumbnail" />

        <v-card-title v-tooltip:bottom="name">
            {{ name }}
        </v-card-title>

        <v-card-actions class="flex justify-between">
            <v-btn>
                {{ work.username }}
            </v-btn>
            <div class="flex gap-2 pr-2" style="zoom: 0.75;">
                <v-badge color="info" :content="work.views" label="浏览量">
                    <v-icon icon="mdi-eye"/>
                </v-badge>
                <v-badge color="primary" :content="work.likes" label="点赞数">
                    <v-icon icon="mdi-heart"/>
                </v-badge>
                <v-badge color="error" :content="work.unlikes" label="点赞数">
                    <v-icon icon="mdi-thumb-down"/>
                </v-badge>
                <v-badge color="success" :content="work.comments" label="评论数">
                    <v-icon icon="mdi-comment-text"/>
                </v-badge>
            </div>
        </v-card-actions>
    </v-card>
</template>

<style scoped></style>

// src/components/WorkCard.tsx
import * as React from 'react';
import { Card, OverlayTrigger, Tooltip } from 'react-bootstrap';
import { getWorkLink } from '@/utils';
import { Work } from '@/interfaces/work';

const WorkCard = ({ work }: { work: Work }) => {
    let link = getWorkLink(work);
    let author_url = `/space.html?id=${work.user_id}`;

    return (
        <Card className="mb-3">
            <OverlayTrigger overlay={<Tooltip>{work.created_at}</Tooltip>}>
                <img
                    src={
                        work.thumbnail ||
                        'https://static0-test.xesimg.com/programme/assets/c16477eaab146fbc22a050e2203f91b8.png'
                    }
                    className="card-img-top"
                    alt={work.name}
                    width={224}
                    height={168}
                />
            </OverlayTrigger>

            <Card.Body>
                <Card.Title>
                    <a href={link} className="text-decoration-none stretched-link" target="_blank">
                        {work.name}
                    </a>
                </Card.Title>
                <Card.Text className="d-flex justify-content-between align-items-center">
                    <a href={author_url} target="_blank" style={{ maxWidth: '114px', zIndex: 2 }}>
                        <span style={{ fontSize: '14px' }}>{work.username}</span>
                    </a>
                    <span style={{ fontSize: '12px' }}>
                        👀{work.views} 👍{work.likes} 👎{work.unlikes} 💬{work.comments}
                    </span>
                </Card.Text>
            </Card.Body>
        </Card>
    );
};

const RemovedWorkCard = () => {
    return (
        <Card className="mb-3" body>
            作品已被下架
        </Card>
    );
};

const SmallWorkCard = ({ work }: { work: Work }) => {
    return (
        <OverlayTrigger
            overlay={
                <Tooltip>
                    👀{work.views} 👍{work.likes} 👎{work.unlikes}
                    <br />
                    {work.created_at}
                </Tooltip>
            }
        >
            <Card>
                <Card.Header>
                    <a href={getWorkLink(work)} className="stretched-link">
                        {work.name}
                    </a>
                </Card.Header>
                <Card.Body className="py-0">
                    <img src={work.thumbnail} height={138} className="m-auto" alt={work.name} />
                </Card.Body>
            </Card>
        </OverlayTrigger>
    );
};

export default WorkCard;
export { RemovedWorkCard, SmallWorkCard };
