// src/pages/code.xueersi.com/user.vue
<script setup lang="ts">
import UserPageWorkCard from '@/components/work/UserPageWorkCard.vue';
import WorkList from '@/components/work/WorkList.vue';
import { useAlertsStore } from '@/stores/alerts';
import { Work, WorkList as IWorkList } from '@/types/work';
import { useFetchData } from '@/utils';
import { computed, onMounted, ref, watch } from 'vue';

const alertsStore = useAlertsStore();

const type = ref('normal');
const lang = ref('projects');
const status = ref('all');
const currentPage = ref(1);
const refreshKey = ref(0);
const [userWorkData, loadUserWorkData] = useFetchData<IWorkList>(() => {
    return `/api/${lang.value}/my?type=${type.value}&published=${status.value}&page=${currentPage.value}&per_page=20`;
});

const totalPages = computed(() =>
    Math.max(Math.ceil((userWorkData.value.data ? userWorkData.value.data.total : 0) / 20), 1),
);

async function handleCancelPublish(work: Work) {
    try {
        await fetch(`/api/${lang.value}/${work.id}/cancel_publish`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                params: {
                    id: work.id,
                },
            }),
        });
        alertsStore.addAlert({
            type: 'success',
            text: '取消发布成功',
            closable: true,
        });
        refreshKey.value++;
    } catch (error) {
        alertsStore.addAlert({
            type: 'error',
            text: '取消发布失败',
            closable: true,
        });
    }
}

watch(type, () => {
    loadUserWorkData();
    currentPage.value = 1;
});
watch(lang, () => {
    loadUserWorkData();
    currentPage.value = 1;
});
watch(status, () => {
    loadUserWorkData();
    currentPage.value = 1;
});
watch(currentPage, () => {
    loadUserWorkData();
});
watch(refreshKey, () => {
    loadUserWorkData();
});
onMounted(() => {
    loadUserWorkData();
});
</script>

<template>
    <v-tabs v-model="type">
        <v-tab value="normal">个人创作</v-tab>
        <v-tab value="homework" v-tooltip:bottom="'（隋唐练习）'">随堂练习</v-tab>
    </v-tabs>
    <v-card class="mb-3 shadow-1">
        <v-card-text>
            <div class="flex gap-4 items-center">
                <span>类型</span>
                <v-tabs v-model="lang">
                    <v-tab value="projects">TurboWarp</v-tab>
                    <v-tab value="python">Python</v-tab>
                    <v-tab value="compilers">C++</v-tab>
                </v-tabs>
            </div>
            <div class="flex gap-4 items-center">
                <span>状态</span>
                <v-tabs v-model="status">
                    <v-tab value="all">全部</v-tab>
                    <v-tab value="0">未发布</v-tab>
                    <v-tab value="2">审核中</v-tab>
                    <v-tab value="1">已发布</v-tab>
                    <v-tab value="removed">已下架</v-tab>
                </v-tabs>
            </div>
        </v-card-text>
    </v-card>

    <WorkList
        :works="(userWorkData.data?.data as unknown as Work[]) || []"
        enable-removed
        :-work-card-interface="UserPageWorkCard"
        @cancel-publish="handleCancelPublish"
        refresh-key="refreshKey"
    />

    <v-pagination v-model="currentPage" :length="totalPages" rounded :total-visible="7" />
</template>

<style scoped></style>

// app/routes/user.tsx
import * as React from 'react';
import { Container, Nav, Card, OverlayTrigger, Tooltip, Button, Badge } from 'react-bootstrap';
import NavbarComponent from '@/components/Navbar';
import WorkList from '@/components/WorkList';
import ProjectPublishModal from '@/components/ProjectPublishModal';
import { Pagination } from '@/components/Pagination';
import AutoCloseAlert from '@/components/AutoCloseAlert';
import { getWorkLink, getEditWorkLink } from '@/utils';
import { v4 as uuidV4 } from 'uuid';

import type { UserWorkList } from '@/interfaces/user';
import type { Work, PublishWorkInfo } from '@/interfaces/work';
import '@/styles/user.scss';

const FixedWorkCard = (
    onClickPublish: (work: PublishWorkInfo) => void,
    onClickCancelPublish: (work: PublishWorkInfo) => void,
) => {
    return ({ work }: { work: Work }) => {
        const publishedText = { 0: '未发布', 1: '已发布', 2: '审核中', removed: '已下架' };
        const [isShowOperators, setIsShowOperators] = React.useState(false);
        let link = getWorkLink(work);
        let editLink = getEditWorkLink(work);
        let workStatus = '';

        if (work.removed) {
            workStatus = publishedText['removed'];
        } else {
            workStatus = publishedText[work.published];
        }

        return (
            <OverlayTrigger
                overlay={<Tooltip>{work.created_at}</Tooltip>}
                onToggle={value => setIsShowOperators(value)}
            >
                <div style={{ position: 'relative' }} className="mb-3">
                    <Card>
                        <img
                            src={
                                work.thumbnail ||
                                'https://static0-test.xesimg.com/programme/assets/c16477eaab146fbc22a050e2203f91b8.png'
                            }
                            className="card-img-top"
                            alt={work.name}
                            width={224}
                            height={168}
                        />

                        <div className="operators-box" style={{ display: isShowOperators ? 'flex' : 'none' }}>
                            <Button variant="" size="sm" onClick={() => window.open(editLink, '_blank')}>
                                编辑
                            </Button>
                            {work.published === 0 && (
                                <Button
                                    variant=""
                                    size="sm"
                                    onClick={() => {
                                        let workData = work as unknown as PublishWorkInfo;
                                        workData.created_source = 'original';
                                        onClickPublish(workData);
                                    }}
                                >
                                    发布
                                </Button>
                            )}
                            {work.published === 1 && (
                                <Button
                                    variant=""
                                    size="sm"
                                    onClick={() => {
                                        let workData = work as unknown as PublishWorkInfo;
                                        onClickCancelPublish(workData);
                                    }}
                                >
                                    取消发布
                                </Button>
                            )}
                        </div>

                        <Card.Body>
                            <Card.Title>
                                <a href={link} className="text-decoration-none stretched-link" target="_blank">
                                    {work.name}
                                </a>
                            </Card.Title>
                            <Card.Text className="d-flex justify-content-between align-items-center">
                                <span style={{ fontSize: '14px' }}>{work.username}</span>
                                <div>
                                    <Badge pill bg="info">
                                        👀{work.views}
                                    </Badge>
                                    <Badge pill bg="primary">
                                        👍{work.likes}
                                    </Badge>
                                    <Badge pill bg="danger">
                                        👎{work.unlikes}
                                    </Badge>
                                    <Badge pill bg="success">
                                        💬{work.comments}
                                    </Badge>
                                </div>
                            </Card.Text>
                        </Card.Body>
                    </Card>
                    <div className="work-status">{workStatus}</div>
                </div>
            </OverlayTrigger>
        );
    };
};

export default function UserPage() {
    const [type, setType] = React.useState('normal');
    const [lang, setLang] = React.useState('projects');
    const [status, setStatus] = React.useState('all');
    const [currentPage, setCurrentPage] = React.useState(1);
    const [pageComponent, setPageComponent] = React.useState(<h2>Loading...</h2>);
    const [showPublishModal, setShowPublishModal] = React.useState(false);
    const [alerts, setAlerts] = React.useState<React.JSX.Element[]>([]);
    const publishWork = React.useRef<PublishWorkInfo>(null);

    React.useEffect(() => {
        let ignore = false;
        const func = async () => {
            const response = await fetch(
                `/api/${lang}/my?type=${type}&published=${status}&page=${currentPage}&per_page=20`,
            );
            const responseData: UserWorkList = await response.json();

            if (responseData.data.total === 0) {
                setPageComponent(<h2>暂时没有作品，快去创作吧</h2>);
                return;
            }
            setPageComponent(
                <>
                    <WorkList
                        works={responseData.data.data}
                        enableRemoved={false}
                        WorkCardInterface={FixedWorkCard(
                            (work: PublishWorkInfo) => {
                                publishWork.current = work;
                                setShowPublishModal(true);
                            },
                            async (work: PublishWorkInfo) => {
                                await fetch(`/api/${lang}/${work.id}/cancel_publish`, {
                                    method: 'POST',
                                    headers: { 'Content-Type': 'application/json' },
                                    body: JSON.stringify({
                                        params: {
                                            id: work.id,
                                        },
                                    }),
                                });
                                setAlerts([
                                    <AutoCloseAlert key={uuidV4()} variant="suceess">
                                        已取消发布
                                    </AutoCloseAlert>,
                                    ...alerts,
                                ]);
                                setLang(work.lang);
                            },
                        )}
                    />
                    {responseData.data.total > 20 && (
                        <Pagination
                            pageCount={Math.ceil(responseData.data.total / 20)}
                            value={currentPage}
                            handlePageChange={value => setCurrentPage(value)}
                            className="mt-2"
                        />
                    )}
                </>,
            );
        };

        if (!ignore) func();
        return () => {
            ignore = true;
        };
    }, [type, lang, status, currentPage]);

    return (
        <>
            <div className="alert-list">{alerts}</div>
            <NavbarComponent />
            {showPublishModal && (
                <ProjectPublishModal
                    workInfo={publishWork.current as PublishWorkInfo}
                    isShow={showPublishModal}
                    setIsShow={setShowPublishModal}
                />
            )}
            <Container className="mt-5">
                <Card body className="shadow-sm mb-3">
                    <Nav
                        className="mb-2"
                        variant="pills"
                        defaultActiveKey="normal"
                        onSelect={eventKey => setType(eventKey || 'normal')}
                    >
                        <Nav.Item>
                            <Nav.Link eventKey="normal">个人创作</Nav.Link>
                        </Nav.Item>
                        <Nav.Item>
                            <OverlayTrigger overlay={<Tooltip>（隋唐练习）</Tooltip>}>
                                <Nav.Link eventKey="homework">随堂练习</Nav.Link>
                            </OverlayTrigger>
                        </Nav.Item>
                    </Nav>

                    <div className="mb-2 d-flex align-items-center">
                        <span>类型</span>
                        <Nav
                            className="custom-nav"
                            defaultActiveKey="projects"
                            onSelect={eventKey => setLang(eventKey || 'projects')}
                        >
                            <Nav.Item>
                                <Nav.Link eventKey="projects">TurboWarp</Nav.Link>
                            </Nav.Item>
                            <Nav.Item>
                                <Nav.Link eventKey="python">Python</Nav.Link>
                            </Nav.Item>
                            <Nav.Item>
                                <Nav.Link eventKey="compilers">C++</Nav.Link>
                            </Nav.Item>
                        </Nav>
                    </div>

                    <div className="d-flex align-items-center">
                        <span>状态</span>
                        <Nav
                            className="custom-nav"
                            defaultActiveKey="all"
                            onSelect={eventKey => setStatus(eventKey || 'all')}
                        >
                            <Nav.Item>
                                <Nav.Link eventKey="all">全部</Nav.Link>
                            </Nav.Item>
                            <Nav.Item>
                                <Nav.Link eventKey="0">未发布</Nav.Link>
                            </Nav.Item>
                            <Nav.Item>
                                <Nav.Link eventKey="2">审核中</Nav.Link>
                            </Nav.Item>
                            <Nav.Item>
                                <Nav.Link eventKey="1">已发布</Nav.Link>
                            </Nav.Item>
                            <Nav.Item>
                                <Nav.Link eventKey="removed">已下架</Nav.Link>
                            </Nav.Item>
                        </Nav>
                    </div>
                </Card>
                {pageComponent}
            </Container>
        </>
    );
}
