// src/pages/Login.vue
<script setup lang="ts">
import { ref, useTemplateRef, watch } from 'vue';
import { useAppStore } from '@/stores/app.ts';
import { refreshInfo } from '@/utils/passport.ts';
import type { LoginPacket } from '@/types/login.ts';
import type { CaptchaPacket } from '@/types/login.ts';

const store = useAppStore();

const formRef = useTemplateRef('form');

const symbol = ref('');
const password = ref('');
const isAgreedPrivacy = ref(false);
const isAgreedEula = ref(false);
const captchaAnswer = ref('');

const isCaptchaVisible = ref(false);
const captchaBase64 = ref('');

const successMessage = ref('');
const errorMessage = ref('');

const isRedirecting = ref(false);

const phoneRule = (value: string) => {
    if (value.trim().length === 11 && !isNaN(parseInt(value))) return true;
    return '不合法的手机号！';
};

const captchaRule = (value: string) => {
    if (value.trim().length === 4) return true;
    return '不合法的验证码！';
};

const requiredRule = (message: string) => {
    return (value: string) => {
        if (value) return true;
        return message;
    };
};
const processCaptcha = async () => {
    const tokenCodeRequest = await fetch('https://passport.100tal.com/v1/web/login/pwd', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            'client-id': '111101',
            'device-id': '_',
            'ver-num': '0.0.0',
        },
        body: new URLSearchParams({
            symbol: symbol.value,
            password: password.value,
            captcha: captchaAnswer.value,
        }).toString(),
    });
    const tokenCodeResult: LoginPacket = await tokenCodeRequest.json();

    if (tokenCodeResult.errcode !== 0) {
        errorMessage.value = tokenCodeResult.errmsg;
        captchaAnswer.value = '';
        isCaptchaVisible.value = false;
    } else {
        successMessage.value = '登录成功！正在跳转到主页...';
        errorMessage.value = '';

        isRedirecting.value = true;

        await fetch('/V1/Web/getToken', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                'client-id': '111101',
                'device-id': '_',
                'ver-num': '0.0.0',
            },
            body: `code=${tokenCodeResult.data.code}`,
        });

        await refreshInfo();

        setTimeout(() => {
            location.href = 'https://code.xueersi.com/';
        }, 500);
    }
};

const getCaptcha = async () => {
    const captchaRequest = await fetch('https://passport.100tal.com/v1/web/captcha/get', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            'client-id': '111101',
            'device-id': '_',
            'ver-num': '0.0.0',
        },
        body: `symbol=${symbol.value}&password=${password.value}&scene=3`,
    });
    const captchaResult: CaptchaPacket = await captchaRequest.json();

    isCaptchaVisible.value = true;
    captchaBase64.value = captchaResult.data.captcha;
};

watch(
    () => store.loaded,
    () => {
        if (!store.isLoggedIn || isRedirecting.value) return;
        successMessage.value = '您已登录！正在跳转到主页...';
        isRedirecting.value = true;

        setTimeout(() => {
            location.href = 'https://code.xueersi.com/';
        }, 500);
    },
);

watch([symbol, password], () => {
    isCaptchaVisible.value = false;
    captchaAnswer.value = '';
});

const onSubmit = () => {
    if (!formRef.value?.isValid) return;

    if (!isCaptchaVisible.value) {
        getCaptcha();
    } else {
        processCaptcha();
    }
};
</script>

<template>
    <div class="flex w-full h-full justify-center items-center">
        <v-card class="min-w-sm max-h-fit mx-auto" elevation="8">
            <v-card-title>
                <h2 class="w-full text-center" style="font-size: 24px">欢迎登录 NewXesFrontend</h2>
            </v-card-title>

            <v-divider />

            <v-card-text>
                <v-form class="flex flex-col gap-2" @submit.prevent="onSubmit" ref="form">
                    <v-alert v-if="successMessage" :text="successMessage" type="success" />
                    <v-alert v-if="errorMessage" :text="errorMessage" type="error" />

                    <v-text-field
                        v-model="symbol"
                        type="text"
                        label="手机号"
                        name="symbol"
                        hide-details="auto"
                        :rules="[phoneRule]"
                    />

                    <v-text-field
                        v-model="password"
                        type="password"
                        label="密码"
                        name="password"
                        hide-details="auto"
                        :rules="[requiredRule('密码不能为空！')]"
                    />

                    <v-text-field
                        v-model="captchaAnswer"
                        type="text"
                        label="验证码"
                        hide-details="auto"
                        :rules="[captchaRule]"
                        v-if="isCaptchaVisible"
                    >
                        <template v-slot:append>
                            <!--<span>我是...终将升起的<del>烈阳</del>验证码！（</span>-->
                            <img :src="captchaBase64" class="h-10" alt="验证码" />
                        </template>
                    </v-text-field>

                    <v-checkbox
                        v-model="isAgreedPrivacy"
                        hide-details="auto"
                        :rules="[requiredRule('请阅读并同意相关协议！')]"
                    >
                        <template v-slot:label>
                            <div>
                                我已阅读并同意以下条款：
                                <div class="flex flex-col" style="font-size: 12px">
                                    <a
                                        href="https://app.xueersi.com/xueersi-mall-hm-xbjtoxes/agreement"
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        style="margin: 0 4px; color: #1976d2"
                                    >
                                        《学而思网校用户协议》、
                                    </a>
                                    <a
                                        href="https://app.xueersi.com/xueersi-mall-hm-xbjtoxes/privacy"
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        style="margin: 0 4px; color: #1976d2"
                                    >
                                        《用户个人信息保护政策》、
                                    </a>
                                    <a
                                        href="https://app.xueersi.com/xueersi-mall-hm-xbjtoxes/childpolicy"
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        style="margin: 0 4px; color: #1976d2"
                                    >
                                        《儿童个人信息保护规则》
                                    </a>
                                </div>
                            </div>
                        </template>
                    </v-checkbox>

                    <v-checkbox
                        v-model="isAgreedEula"
                        hide-details="auto"
                        :rules="[requiredRule('请阅读并同意本协议！')]"
                    >
                        <template v-slot:label>
                            <div>
                                我已阅读并同意 <br />
                                <a
                                    href="/eula"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    style="margin: 0 4px; color: #1976d2; font-size: 12px"
                                >
                                    《NewXesFrontend 最终用户协议》
                                </a>
                            </div>
                        </template>
                    </v-checkbox>

                    <v-btn type="submit" color="primary">登录</v-btn>
                </v-form>
            </v-card-text>
        </v-card>
    </div>
</template>

<style scoped></style>

// src/login.tsx
import React from 'react';
import { createRoot } from 'react-dom/client';
import { Form, Row, Col, Button, InputGroup, Alert } from 'react-bootstrap';
import { CaptchaPacket, LoginPacket } from './interfaces/login.ts';
import { checkLoggedIn } from './utils.ts';
import './styles/login.scss';

const LoginPage = () => {
    const [symbolValue, setSymbolValue] = React.useState('');
    const [passwordValue, setPasswordValue] = React.useState('');
    const [privacyValue, setPrivacyValue] = React.useState(false);

    const [captchaBase64, setCaptchaBase64] = React.useState('');
    const [captchaAnswer, setCaptchaAnswer] = React.useState('');

    const [errorValue, setErrorValue] = React.useState('');
    const [successValue, setSuccessValue] = React.useState('');

    const [visuallyValue, setVisuallyValue] = React.useState(true);
    const [passportReadOnly, setPassportReadOnly] = React.useState(false);
    const [requiredCaptcha, setRequiredCaptcha] = React.useState(false);

    const processCaptcha = async () => {
        const tokenCodeRequest = await fetch('/passport/login', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                'client-id': '111101',
                'device-id': '_',
                'ver-num': '0.0.0',
            },
            body: `symbol=${symbolValue}&password=${passwordValue}&captcha=${captchaAnswer}`,
        });
        const tokenCodeResult: LoginPacket = await tokenCodeRequest.json();

        if (tokenCodeResult.errcode !== 0) {
            setErrorValue(tokenCodeResult.errmsg);
            setPassportReadOnly(false);
            setRequiredCaptcha(false);
            setVisuallyValue(true);
            setCaptchaAnswer('');
        } else {
            setSuccessValue('登录成功！正在跳转到主页...');

            await fetch('/passport/get_token', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                    'client-id': '111101',
                    'device-id': '_',
                    'ver-num': '0.0.0',
                },
                body: `code=${tokenCodeResult.data.code}`,
            });

            setTimeout(() => {
                location.href = '/';
            }, 500);
        }
    };

    const loginEvent = async (event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault();

        if (symbolValue.length !== 11) {
            setErrorValue('不合法的手机号！');
            return;
        } else if (passwordValue === '') {
            setErrorValue('密码不能为空！');
            return;
        } else if (requiredCaptcha && captchaAnswer === '') {
            setErrorValue('验证码不能为空！');
            return;
        } else if (!privacyValue) {
            setErrorValue('请阅读并同意相关协议！');
            return;
        } else {
            setErrorValue('');
        }

        if (requiredCaptcha) {
            await processCaptcha();
            return;
        }

        const captchaRequest = await fetch('/passport/captcha', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                'client-id': '111101',
                'device-id': '_',
                'ver-num': '0.0.0',
            },
            body: `symbol=${symbolValue}&password=${passwordValue}&scene=3`,
        });
        const captchaResult: CaptchaPacket = await captchaRequest.json();

        setVisuallyValue(false);
        setPassportReadOnly(true);
        setRequiredCaptcha(true);
        setCaptchaBase64(captchaResult.data.captcha);
    };

    React.useEffect(() => {
        if (checkLoggedIn()) {
            setSuccessValue('您已登录！正在跳转到主页...');
            setTimeout(() => {
                location.href = '/';
            }, 500);
        }
    }, []);

    return (
        <>
            <Row className="justify-content-md-center width-100 height-100">
                <Col xs={12} sm={8} md={6} lg={4} className="login-form-container shadow margin-auto">
                    <h1>欢迎登录 NewXesFrontend</h1>

                    <Form onSubmit={loginEvent}>
                        <Alert variant="danger" hidden={errorValue ? false : true}>
                            {errorValue}
                        </Alert>
                        <Alert variant="success" hidden={successValue ? false : true}>
                            {successValue}
                        </Alert>

                        <InputGroup>
                            <InputGroup.Text>手机号</InputGroup.Text>
                            <Form.Control
                                type="number"
                                name="symbol"
                                title="手机号"
                                placeholder="13333333333"
                                disabled={passportReadOnly}
                                value={symbolValue}
                                onChange={event => setSymbolValue(event.target.value)}
                            />
                        </InputGroup>

                        <InputGroup>
                            <InputGroup.Text>密码</InputGroup.Text>
                            <Form.Control
                                type="password"
                                name="password"
                                title="密码"
                                placeholder="123456"
                                disabled={passportReadOnly}
                                value={passwordValue}
                                onChange={event => setPasswordValue(event.target.value)}
                            />
                        </InputGroup>

                        <Form.Check
                            type="checkbox"
                            name="我已阅读并同意各种条款"
                            title="我已阅读并同意各种条款"
                            disabled={passportReadOnly}
                            label={
                                <div>
                                    我已阅读并同意
                                    <a
                                        href="https://app.xueersi.com/xueersi-mall-hm-xbjtoxes/agreement"
                                        target="_blank"
                                    >
                                        《学而思网校用户协议》
                                    </a>
                                    、
                                    <a href="https://app.xueersi.com/xueersi-mall-hm-xbjtoxes/privacy" target="_blank">
                                        《用户个人信息保护政策》
                                    </a>
                                    、
                                    <a
                                        href="https://app.xueersi.com/xueersi-mall-hm-xbjtoxes/childpolicy"
                                        target="_blank"
                                    >
                                        《儿童个人信息保护规则》
                                    </a>
                                    、
                                    <a href="/eula.html" target="_blank">
                                        《NewXesFrontend 最终用户协议》
                                    </a>
                                    、
                                </div>
                            }
                            value={Number(privacyValue)}
                            onChange={event => setPrivacyValue(event.target.checked)}
                        />

                        <InputGroup hidden={visuallyValue}>
                            <InputGroup.Text>验证码</InputGroup.Text>
                            <InputGroup.Text>
                                <img src={captchaBase64} alt="验证码" />
                            </InputGroup.Text>
                            <Form.Control
                                type="text"
                                name="captcha"
                                title="验证码"
                                placeholder="abcd"
                                value={captchaAnswer}
                                onChange={event => setCaptchaAnswer(event.target.value)}
                            />
                        </InputGroup>

                        <Button type="submit" variant="primary">
                            登录
                        </Button>
                    </Form>
                </Col>
            </Row>
        </>
    );
};

const dom: HTMLElement | null = document.getElementById('app');
if (dom) {
    const root = createRoot(dom);
    root.render(<LoginPage />);
} else {
    throw new Error('Cannot find dom element #app');
}
