// src/components/WorkList.tsx
import React from 'react';
import { Work } from '../interfaces/work.ts';
import { Row, Col } from 'react-bootstrap';
import WorkCard from './WorkCard.tsx';
import { RemovedWorkCard } from './WorkCard.tsx';

const WorkList = ({ works, className = '' }: { works: Work[]; className?: string }) => {
    const cards = works.map((work: Work) => {
        if (work.removed) {
            return (
                <Col key={work.topic_id}>
                    <RemovedWorkCard />
                </Col>
            );
        };
        return (
            <Col key={work.id}>
                <WorkCard work={work} />
            </Col>
        );
    });

    return (
        <Row xs={1} sm={2} md={3} lg={4} xl={5} className={className}>
            {cards}
        </Row>
    );
};

export default WorkList;

// src/components/work/WorkList.vue
﻿<script setup lang="ts">
import type { Work } from '@/types/work.ts';
import WorkCard from '@/components/work/WorkCard.vue';
import RemovedWorkCard from '@/components/work/RemovedWorkCard.vue';

interface Props {
    className?: string;
    works: Work[];
}

const { className = 'm-4 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-2', works } =
    defineProps<Props>();
</script>

<template>
    <div :class="className">
        <component
            v-for="work of works"
            :key="work.id"
            :is="work.removed ? RemovedWorkCard : WorkCard"
            :work="work"
        />
    </div>
</template>

<style scoped></style>
