// app/layout/AppNavbar.tsx
import * as React from 'react';
import { AppBar, Avatar, Badge, Menu, MenuItem, IconButton, Divider, Button, Toolbar, Box } from '@mui/material';
import { NavLink } from 'react-router';
import SearchInput from '@/components/SearchInput';
import { checkLoggedIn } from '@/utils';

import type { UserInfo } from '@/interfaces/user';
import type { MessageData } from '@/interfaces/message';
import '@/styles/search.css';

const UserMenu = ({
    userInfo,
    messageData,
    totalMessageCount,
    onLogout,
}: {
    userInfo: UserInfo['data'];
    messageData: MessageData | null;
    totalMessageCount: number;
    onLogout: () => void;
}) => {
    const [anchorEl, setAnchorEl] = React.useState<null | HTMLElement>(null);
    const openUserMenu = Boolean(anchorEl);

    const [messageEl, setMessageEl] = React.useState<null | HTMLElement>(null);
    const openMessageMenu = Boolean(messageEl);

    return (
        <>
            <Button
                aria-controls={openMessageMenu ? 'basic-menu' : undefined}
                aria-haspopup="true"
                aria-expanded={openMessageMenu ? 'true' : undefined}
                onClick={event => setMessageEl(event.currentTarget)}
            >
                <Badge color="error" badgeContent={totalMessageCount}>
                    <span>消息</span>
                </Badge>
            </Button>
            <Menu
                anchorEl={messageEl}
                open={openMessageMenu}
                onClose={() => setMessageEl(null)}
                slotProps={{
                    list: {
                        'aria-labelledby': 'basic-button',
                    },
                }}
            >
                <MenuItem component={NavLink} to="/message/1">
                    <Badge color="error" badgeContent={messageData?.data[0].count}>
                        评论和回复
                    </Badge>
                </MenuItem>
                <MenuItem component={NavLink} to="/message/5">
                    <Badge color="error" badgeContent={messageData?.data[2].count}>
                        关注
                    </Badge>
                </MenuItem>
            </Menu>

            <IconButton
                aria-controls={openUserMenu ? 'basic-menu' : undefined}
                aria-haspopup="true"
                aria-expanded={openUserMenu ? 'true' : undefined}
                onClick={event => setAnchorEl(event.currentTarget)}
            >
                <Avatar alt={userInfo.name} src={userInfo.avatar_path} sx={{ width: 40, height: 40 }} />
            </IconButton>
            <Menu
                anchorEl={anchorEl}
                open={openUserMenu}
                onClose={() => setAnchorEl(null)}
                slotProps={{
                    list: {
                        'aria-labelledby': 'basic-button',
                    },
                }}
            >
                <MenuItem component={NavLink} to={`/space/${userInfo.id}/home`}>
                    个人空间
                </MenuItem>
                <MenuItem component={NavLink} to="/user">
                    作品管理
                </MenuItem>
                <Divider />
                <MenuItem component={NavLink} to="/userInfo">
                    个人信息
                </MenuItem>
                <Divider />
                <MenuItem onClick={onLogout}>登出</MenuItem>
            </Menu>
        </>
    );
};

const CreateMenu = () => {
    const [anchorEl, setAnchorEl] = React.useState<null | HTMLElement>(null);
    const openCreateMenu = Boolean(anchorEl);

    return (
        <>
            <Button
                aria-controls={openCreateMenu ? 'basic-menu' : undefined}
                aria-haspopup="true"
                aria-expanded={openCreateMenu ? 'true' : undefined}
                onClick={event => setAnchorEl(event.currentTarget)}
            >
                <span>创作</span>
            </Button>
            <Menu
                anchorEl={anchorEl}
                open={openCreateMenu}
                onClose={() => setAnchorEl(null)}
                slotProps={{
                    list: {
                        'aria-labelledby': 'basic-button',
                    },
                }}
            >
                <MenuItem component={NavLink} to="#">
                    TurboWarp
                </MenuItem>
                <Divider />
                <MenuItem component={NavLink} to="#">
                    Python 基础
                </MenuItem>
                <MenuItem component={NavLink} to="#">
                    Python 海龟
                </MenuItem>
                <MenuItem component={NavLink} to="#">
                    Python 本地
                </MenuItem>
                <Divider />
                <MenuItem component={NavLink} to="#">
                    C++
                </MenuItem>
            </Menu>
        </>
    );
};

const AppNavbar = () => {
    const [userInfo, setUserInfo] = React.useState<UserInfo['data'] | null>(null);
    const [messageData, setMessageData] = React.useState<MessageData | null>(null);
    const [totalMessageCount, setTotalMessageCount] = React.useState(0);

    const logoutEvent = async () => {
        await fetch('/passport/logout');
        location.reload();
    };

    React.useEffect(() => {
        const fetchData = async () => {
            if (checkLoggedIn()) {
                const response = await fetch('/api/user/info');
                const userData: UserInfo = await response.json();
                setUserInfo(userData.data);

                if (!location.pathname.includes('message.html')) {
                    const messageResponse = await fetch(`/api/messages/overview`);
                    const messageResponseData: MessageData = await messageResponse.json();
                    setMessageData(messageResponseData);
                    setTotalMessageCount(messageResponseData.data.reduce((acc, cur) => acc + cur.count, 0));
                }
            }
        };

        fetchData();
    }, []);

    return (
        <AppBar className="shadow" position="static">
            <div className="container mx-auto">
                <Toolbar>
                    <NavLink to="/" className="mr-2">
                        <span style={{ fontSize: '24px' }}>XesCoding</span>
                    </NavLink>

                    <Box className="me-auto flex gap-2">
                        <Button sx={{ display: 'block' }} onClick={() => (location.href = '/')}>
                            首页
                        </Button>

                        <Button sx={{ display: 'block' }} onClick={() => (location.href = '/discover')}>
                            发现
                        </Button>

                        <Button sx={{ display: 'block' }} onClick={() => (location.href = '/about')}>
                            关于
                        </Button>
                    </Box>

                    <Box className="ms-auto flex gap-2">
                        <SearchInput />

                        {userInfo ? (
                            <UserMenu
                                userInfo={userInfo}
                                messageData={messageData}
                                totalMessageCount={totalMessageCount}
                                onLogout={logoutEvent}
                            />
                        ) : (
                            <Button sx={{ display: 'block' }} onClick={() => (location.href = '/login')}>
                                登录
                            </Button>
                        )}

                        <CreateMenu />
                    </Box>
                </Toolbar>
            </div>
        </AppBar>
    );
};

export default AppNavbar;

// src/layout/AppNavbar.vue
﻿<script setup lang="ts">
import { computed } from 'vue';
import { useRouter } from 'vue-router';
import { useAppStore } from '@/stores/app.ts';
import { useFetchData } from '@/utils/index.ts';
import SearchInput from '@/components/SearchInput.vue';
import type { MessageData } from '@/types/message.ts';

const store = useAppStore();
const router = useRouter();

const messageData = useFetchData<MessageData[]>('/api/messages/overview');
const messageTotal = computed(() => {
    if (messageData.value.error) return 0;
    return messageData.value.data?.reduce((acc, cur: MessageData) => acc + cur.count, 0);
});

const onClickLogout = async () => {
    await fetch('/passport/logout');
    location.reload();
}
</script>

<template>
    <v-app-bar style="position: static" elevation="4">
        <div class="container mx-auto flex px-4 items-center">
            <router-link to="/" class="mr-2" style="font-size: 24px"> XesCoding </router-link>

            <div class="me-auto flex gap-2 items-center">
                <router-link v-slot="{ navigate, isActive }" to="/" custom>
                    <v-btn :active="isActive" @click="navigate"> 首页 </v-btn>
                </router-link>

                <v-btn> 发现 </v-btn>

                <router-link v-slot="{ navigate, isActive }" to="/about" custom>
                    <v-btn :active="isActive" @click="navigate"> 关于 </v-btn>
                </router-link>
            </div>

            <div class="ms-auto flex gap-2 items-center">
                <SearchInput />

                <v-menu open-on-hover v-if="store.isLoggedIn">
                    <template v-slot:activator="{ props }">
                        <v-btn v-bind="props">
                            <v-badge
                                inline
                                color="error"
                                :content="messageTotal || 0"
                                :model-value="(messageTotal || 0) > 0"
                            >
                                消息
                            </v-badge>
                        </v-btn>
                    </template>

                    <v-list>
                        <v-list-item value="1">
                            <v-badge
                                inline
                                color="error"
                                :content="messageData.data?.[0].count"
                                :model-value="(messageTotal || 0) > 0"
                            >
                                评论和回复
                            </v-badge>
                        </v-list-item>
                        <v-list-item value="5">
                            <v-badge
                                inline
                                color="error"
                                :content="messageData.data?.[2].count"
                                :model-value="(messageTotal || 0) > 0"
                            >
                                关注
                            </v-badge>
                        </v-list-item>
                    </v-list>
                </v-menu>

                <v-menu open-on-hover v-if="store.isLoggedIn">
                    <template v-slot:activator="{ props }">
                        <v-btn v-bind="props" icon>
                            <v-avatar :image="store.userInfo?.avatar_path" />
                        </v-btn>
                    </template>

                    <v-list>
                        <v-list-item value="space"> 个人空间 </v-list-item>
                        <v-list-item value="user"> 作品管理 </v-list-item>
                        <v-divider />
                        <router-link v-slot="{ navigate, isActive }" to="/userInfo" custom>
                            <v-list-item value="info" :active="isActive" @click="_ => navigate()">
                                个人信息
                            </v-list-item>
                        </router-link>
                        <v-divider />
                        <v-list-item value="logout" @click="onClickLogout"> 登出 </v-list-item>
                    </v-list>
                </v-menu>

                <router-link v-slot="{ navigate, isActive }" to="/login" custom v-if="!store.isLoggedIn">
                    <v-btn :active="isActive" @click="navigate"> 登录 </v-btn>
                </router-link>

                <v-menu open-on-hover>
                    <template v-slot:activator="{ props }">
                        <v-btn v-bind="props"> 创作 </v-btn>
                    </template>

                    <v-list>
                        <v-list-item value="1"> TurboWarp </v-list-item>
                        <v-divider />
                        <v-list-item value="5"> Python 基础 </v-list-item>
                        <v-list-item value="5"> Python 海龟 </v-list-item>
                        <v-list-item value="5"> Python 本地 </v-list-item>
                        <v-divider />
                        <v-list-item value="5"> C++ </v-list-item>
                    </v-list>
                </v-menu>
            </div>
        </div>
    </v-app-bar>
</template>

<style scoped></style>
